version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://corleone_user:dQ3loGRYkKNvFXupiXcpRUjmZBw4JXbC@dpg-cmbgi20cmk4c73dgp4pg-a.oregon-postgres.render.com/corleone
      - NAME=World
